using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ESIConnectionLibrary.ESIModels
{
    [JsonConverter(typeof(StringEnumConverter))]
    internal enum EsiLocationFlagCorporation
    {
        AssetSafety,
        AutoFit,
        Bonus,
        Booster,
        BoosterBay,
        Capsule,
        Cargo,
        CorpDeliveries,

        [EnumMember(Value = "CorpSAG1")]
        CorpSag1,

        [EnumMember(Value = "CorpSAG2")]
        CorpSag2,

        [EnumMember(Value = "CorpSAG3")]
        CorpSag3,

        [EnumMember(Value = "CorpSAG4")]
        CorpSag4,

        [EnumMember(Value = "CorpSAG5")]
        CorpSag5,

        [EnumMember(Value = "CorpSAG6")]
        CorpSag6,

        [EnumMember(Value = "CorpSAG7")]
        CorpSag7,
        CrateLoot,
        Deliveries,
        DroneBay,
        DustBattle,
        DustDatabank,
        FighterBay,
        FighterTube0,
        FighterTube1,
        FighterTube2,
        FighterTube3,
        FighterTube4,
        FleetHangar,
        Hangar,
        HangarAll,
        HiSlot0,
        HiSlot1,
        HiSlot2,
        HiSlot3,
        HiSlot4,
        HiSlot5,
        HiSlot6,
        HiSlot7,
        HiddenModifers,
        Implant,
        Impounded,
        JunkyardReprocessed,
        JunkyardTrashed,
        LoSlot0,
        LoSlot1,
        LoSlot2,
        LoSlot3,
        LoSlot4,
        LoSlot5,
        LoSlot6,
        LoSlot7,
        Locked,
        MedSlot0,
        MedSlot1,
        MedSlot2,
        MedSlot3,
        MedSlot4,
        MedSlot5,
        MedSlot6,
        MedSlot7,
        OfficeFolder,
        Pilot,
        PlanetSurface,
        QuafeBay,
        Reward,
        RigSlot0,
        RigSlot1,
        RigSlot2,
        RigSlot3,
        RigSlot4,
        RigSlot5,
        RigSlot6,
        RigSlot7,
        SecondaryStorage,
        ServiceSlot0,
        ServiceSlot1,
        ServiceSlot2,
        ServiceSlot3,
        ServiceSlot4,
        ServiceSlot5,
        ServiceSlot6,
        ServiceSlot7,
        ShipHangar,
        ShipOffline,
        Skill,
        SkillInTraining,
        SpecializedAmmoHold,
        SpecializedCommandCenterHold,
        SpecializedFuelBay,
        SpecializedGasHold,
        SpecializedIndustrialShipHold,
        SpecializedLargeShipHold,
        SpecializedMaterialBay,
        SpecializedMediumShipHold,
        SpecializedMineralHold,
        SpecializedOreHold,
        SpecializedPlanetaryCommoditiesHold,
        SpecializedSalvageHold,
        SpecializedShipHold,
        SpecializedSmallShipHold,
        StructureActive,
        StructureFuel,
        StructureInactive,
        StructureOffline,
        SubSystemSlot0,
        SubSystemSlot1,
        SubSystemSlot2,
        SubSystemSlot3,
        SubSystemSlot4,
        SubSystemSlot5,
        SubSystemSlot6,
        SubSystemSlot7,
        SubsystemBay,
        Unlocked,
        Wallet,
        Wardrobe
    }
}