namespace ESIConnectionLibrary.PublicModels
{
    public enum V2UniverseStationServices
    {
        bountyMissions,
        assasinationMissions,
        courierMissions,
        interbus,
        reprocessingPlant,
        refinery,
        market,
        blackMarket,
        stockExchange,
        cloning,
        surgery,
        dnaTherapy,
        repairFacilities,
        factory,
        labratory,
        gambling,
        fitting,
        paintshop,
        news,
        storage,
        insurance,
        docking,
        officeRental,
        jumpCloneFacility,
        loyaltyPointStore,
        navyOffices,
        securityOffices
    }
}